# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  AZURE_WEBAPP_NAME: solid-team-solution
  AZURE_WEBAPP_PACKAGE_PATH: "./publish"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore solid-team-solution/solid-team-solution.sln
        
      - name: Build
        run: dotnet build solid-team-solution/solid-team-solution.sln
        
      - name: Test
        run: dotnet publish solid-team-solution/solid-team-solution.sln --configuration Release --no-restore --output ${{env.AZURE_WEBAPP_PACKAGE_PATH}}
        
      - name: Deploy
        uses: azure/webapps-deploy@v2
        with: 
          app-name: ${{env.AZURE_WEBAPP_NAME}}
          publish-profile: ${{env.AZURE_PUBLISH_PROFILE}}
          package: ${{env.AZURE_WEBAPP_PACKAGE_PATH}}
        

 
